apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: modeldeploy-sample
    app.alauda.io/name: modeldeploy-sample.default
    app.aml: model-deploy
    creator.model-deploy: modeldeploy-sample
  name: chicago-taxi-model # name can not use "_"
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: modeldeploy-sample
      app.aml: model-deploy
      creator.model-deploy: modeldeploy-sample
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        alauda.io/product: Alauda Machine Learning
        alauda.io/product.version: v0.6
      creationTimestamp: null
      labels:
        app: modeldeploy-sample
        app.aml: model-deploy
        creator.model-deploy: modeldeploy-sample
      name: modeldeploy-sample
      namespace: default
    spec:
      containers:
      - args:
        - /usr/bin/tensorflow_model_server
        - --port=8500
        - --rest_api_port=8501
        - --model_name=chicago-taxi
        - --model_base_path=/models/chicago-taxi/
        image: index.alauda.cn/alaudaorg/chicago-taxi-modelserver:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: grpc
          timeoutSeconds: 1
        name: model
        ports:
        - containerPort: 8500
          name: grpc
          protocol: TCP
        - containerPort: 8501
          name: restful
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 20
          successThreshold: 1
          tcpSocket:
            port: grpc
          timeoutSeconds: 1
      - args:
        - server
        - --port=8505
        - --forwardPort=8501
        - --modelname=chicago-taxi
        image: index.alauda.cn/alaudaorg/modelswagger:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: swagger
          timeoutSeconds: 1
        name: swagger
        ports:
        - containerPort: 8505
          name: swagger
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 15
          periodSeconds: 20
          successThreshold: 1
          tcpSocket:
            port: swagger
          timeoutSeconds: 1